//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.14 at 05:03:43 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kravchenko.com/springeshop/ws/greeting", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kravchenko.springeshop.ws.greeting;
